-- AgilePM Practitioner sample paper: "AgilePM3 Practitioner - Paper 1"
-- Generated from AgilePM_v3_Practitioner_Sample_Paper_Harbour_Quarter.md by scripts/build-practitioner-exam.mjs
-- Practitioner objective-test format: shared scenario + 4 questions x parts x 60 items total.

-- Schema support for the Practitioner format
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS scenario text;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS shuffle boolean NOT NULL DEFAULT true;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS option_h text NOT NULL DEFAULT '';
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS question_number integer;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS part text;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS item_type text;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS part_instruction text;

-- Replace any prior copy of this paper (idempotent re-run; cascade clears its questions).
-- Clear this exam's attempts first (exam_attempts FK has no cascade); scoped to this slug only.
DELETE FROM public.exam_attempts WHERE exam_id IN (SELECT id FROM public.exams WHERE slug = 'agilepm-practitioner-paper-1');
DELETE FROM public.exams WHERE slug = 'agilepm-practitioner-paper-1';

INSERT INTO public.exams (id, title, slug, description, scenario, shuffle, duration_minutes, pass_mark, total_questions, status)
VALUES (
  '0a052eda-f115-4e08-bb3b-10c6edf8d20e',
  'AgilePM3 Practitioner - Paper 1',
  'agilepm-practitioner-paper-1',
  'Original practice Practitioner paper using the Harbour Quarter Regeneration scenario. Objective-test format: four scenario-based questions, 60 marks, 50% to pass, 2 hours, open book.',
  'The companies and people in this scenario are fictional.

**Quayside Futures** is a social enterprise led by its Chief Executive, **Marcus Hale**. Its purpose is to regenerate a disused stretch of dockside, the old Custom House and its warehouses, into a public arts, makers and events quarter that blends heritage conservation, community livelihoods and sustainable operation. The vision is set and assured by **Dr Femi Okafor**.

Over three earlier Project Increments the team restored the Custom House as a public gallery, added maker workshops and a café, and opened an events lawn along the quay. Each opened on time and built the Quarter''s reputation for heritage-led, low impact regeneration.

**Project Increment 4** introduces the **Makers'' Wing**, a set of bookable studio residencies, together with a public opening programme of workshops and exhibitions. The Increment must be ready for the autumn arts festival, which is a fixed date. The new offering is expected to draw makers and visitors, lift memberships and income, and keep the Quarter''s standing as a model of sustainable regeneration.

**Scope and deliverables**

- Build and fit out the Makers'' Wing studios using salvaged and locally sourced materials and traditional conservation methods.
- Install accessible visitor facilities that meet heritage and safety standards.
- Launch a membership and online studio booking platform.
- Deliver an opening programme of workshops and exhibitions.
- Embed heritage, safety and accessibility compliance throughout.

**Roles and responsibilities**

| Role | Person | Responsibility |
|------|--------|----------------|
| Business Sponsor | Marcus Hale | Owns the project and its Business Case. CEO of Quayside Futures. |
| Business Visionary | Dr Femi Okafor | Sets and assures the vision and strategic direction for the Quarter. |
| Solution Architect | Greta Lindqvist | Conservation architect. Assures the integrity and quality of the overall solution. |
| Project Manager | Tomas Reyes | Manages timeline, resources, stakeholder engagement and cross-team coordination. |
| Product Owner | Aisha Rahman | Visitor and Programme Manager. Product Owner for both Delivery Teams. |
| Business Advisor, Compliance | Nina Coburn | Heritage, safety and accessibility compliance, spanning the whole enterprise. |
| Business Advisor, Marketing | Sam Doyle | Brand and marketing specialist, part-time and off-site. |
| Process Advisor | Bram Vos | Operations Manager for the Quarter, an operational delivery role. |
| Solution Advisor | Yusuf Demir | Conservation-materials specialist. |
| Delivery Teams | Estate Team and Programme Team | Estate Team: building, conservation, utilities, fit-out. Programme Team: events, membership, retail, IT and booking. |
| Developers | | Trades and conservation craftspeople, programme and curatorial staff, marketing and IT staff. |

---',
  false,
  120, 30, 60, 'published'
);

INSERT INTO public.questions
  (exam_id, area, question_number, part, item_type, part_instruction, question_text, option_a, option_b, option_c, option_d, option_e, option_f, option_g, option_h, correct_answer, reference, status, sort_order)
VALUES
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Keep the Makers'' Wing fit for purpose and avoid gilding the finishes beyond the agreed standard.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'D', 'D, Never Compromise Quality. Quality means fit for purpose and good enough, neither under nor over-engineered. Section 4.3.4.', 'published', 1),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Reinforce Dr Okafor''s vision at every Sprint Planning and Sprint Review so the work stays aligned to the regeneration goals.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'A', 'A, Focus on the Business Need. Decisions stay aligned to the vision, which is kept visible and reinforced. Section 4.3.1.', 'published', 2),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Build a firm, shared understanding of the high-level scope at Foundations before development begins.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'E', 'E, Build Incrementally from Firm Foundations. Foundations establishes enough high-level understanding and scope before building starts. Section 4.3.5, Section 7.5.1.', 'published', 3),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Let the detailed studio layouts emerge during development rather than fixing them at the outset.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'F', 'F, Develop Iteratively. Detail emerges through cycles of feedback rather than being fixed upfront. Section 4.3.6.', 'published', 4),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Display Sprint progress on a shared board that is always visible, rather than relying on written reports.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'H', 'H, Demonstrate Control. Real-time visible transparency is preferred over written reports. Section 4.3.8. Tempting distractor: G, Communicate Continuously and Clearly. The cue here is control through visible progress, which AgilePM ties to Demonstrate Control.', 'published', 5),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part A', 1, 'A', 'match', 'For each action in Column 1, select the AgilePM Principle in Column 2 that best justifies it. Each Principle may be used once, more than once, or not at all.', 'Bring conservation craftspeople and curators into the same workshop to shape the Makers'' Wing together.', 'Focus on the Business Need', 'Deliver on Time', 'Collaborate', 'Never Compromise Quality', 'Build Incrementally from Firm Foundations', 'Develop Iteratively', 'Communicate Continuously and Clearly', 'Demonstrate Control', 'C', 'C, Collaborate. Bringing roles together to shape the solution is collaboration. Section 4.3.3, Section 6.1.1.', 'published', 6),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part B', 1, 'B', 'single', 'Answer the following. There is one correct response to each.', 'Tomas, the Project Manager, is asked to rewrite Product Backlog items himself to speed delivery up. What is the appropriate response?', 'He should rewrite them, because the Project Manager coordinates all aspects of delivery.', 'He should define them, because he has the clearest view of the whole project.', 'No. Backlog refinement sits with the Product Owner, with input from the team. The Project Manager enables delivery and removes blockers.', 'He should delegate the rewrite to the Team Leaders.', '', '', '', '', 'C', 'C. Backlog refinement is the Product Owner''s, with team input. The Project Manager enables delivery and removes blockers, and does not define requirements. Sections 5.4.1 and 5.3.4.', 'published', 7),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part B', 1, 'B', 'single', 'Answer the following. There is one correct response to each.', 'Dr Okafor, the Business Visionary, wants to hand all day-to-day product decisions to Aisha and step back from the project entirely. Is this appropriate?', 'Yes. The Product Owner now owns the vision.', 'The Visionary may delegate the work, but remains accountable for the vision and must stay available to the team.', 'Yes. The vision should pass to the Solution Architect.', 'Yes. The Visionary no longer needs to attend events.', '', '', '', '', 'B', 'B. The Business Visionary may delegate the work but remains accountable for the vision and must stay available. Section 5.3.2.', 'published', 8),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part B', 1, 'B', 'single', 'Answer the following. There is one correct response to each.', 'Greta, the Solution Architect, dismisses a proposed community-garden feature as an unnecessary distraction. Is this within her role?', 'Yes. The Solution Architect decides what is in scope.', 'No. The Solution Architect advises on feasibility and risk. The value decision sits with the Business Visionary and prioritisation with the Product Owner.', 'Yes. The Solution Architect owns the backlog.', 'No. The Project Manager should make that call.', '', '', '', '', 'B', 'B. The Solution Architect advises on feasibility and risk. Judging value sits with the Business Visionary, prioritisation with the Product Owner. Sections 5.3.3, 5.3.2 and 5.4.1.', 'published', 9),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part B', 1, 'B', 'single', 'Answer the following. There is one correct response to each.', 'Who is the stakeholder representative inside the Delivery Team, accountable for maximising the value delivered?', 'The Project Manager.', 'The Business Visionary.', 'The Product Owner.', 'The Team Leader.', '', '', '', '', 'C', 'C. The Product Owner is the stakeholder representative inside the Delivery Team, accountable for maximising value. Section 5.4.1.', 'published', 10),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part B', 1, 'B', 'single', 'Answer the following. There is one correct response to each.', 'Aisha will act as Product Owner for both Delivery Teams. Is one Product Owner across two teams acceptable?', 'No. Each Delivery Team needs its own Product Owner.', 'Yes. One Product Owner can serve both, with coordination through a shared Solution Backlog and Cross-Team Refinement.', 'No. The Project Manager should own the second team''s backlog.', 'Yes, but the teams must avoid coordinating, to stay independent.', '', '', '', '', 'B', 'B. One Product Owner can serve more than one Delivery Team, with coordination through a shared Solution Backlog and Cross-Team Refinement. Sections 5.4.1 and 5.6.', 'published', 11),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part C', 1, 'C', 'match', 'For each situation in Column 1, select the most effective communication method from Column 2. Each method may be used once, more than once, or not at all.', 'Aisha wants to gauge interest from the wider public in a new membership tier before committing to it.', 'Face-to-face', 'Instant messaging', 'Social media', 'Email', 'Collaborative workspace', 'Document', 'Video conference', '', 'C', 'C, Social media. Testing demand with a wide external audience suits a scalable, interactive broadcast channel. Section 6.3.3, Section 6.1.2.', 'published', 12),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part C', 1, 'C', 'match', 'For each situation in Column 1, select the most effective communication method from Column 2. Each method may be used once, more than once, or not at all.', 'A Programme Team member must co-develop launch materials with Sam Doyle over the coming weeks. Sam is part-time, off-site, and an hour ahead.', 'Face-to-face', 'Instant messaging', 'Social media', 'Email', 'Collaborative workspace', 'Document', 'Video conference', '', 'E', 'E, Collaborative workspace. A small time difference and part-time availability suit asynchronous tools that support ongoing contribution. Section 6.3.3.', 'published', 13),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part C', 1, 'C', 'match', 'For each situation in Column 1, select the most effective communication method from Column 2. Each method may be used once, more than once, or not at all.', 'Aisha and Greta, both on site, need to work through the technical feasibility of a salvaged-timber mezzanine.', 'Face-to-face', 'Instant messaging', 'Social media', 'Email', 'Collaborative workspace', 'Document', 'Video conference', '', 'A', 'A, Face-to-face. Co-located technical feasibility work is clearest in direct conversation. Section 6.3.1.', 'published', 14),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 1, Part C', 1, 'C', 'match', 'For each situation in Column 1, select the most effective communication method from Column 2. Each method may be used once, more than once, or not at all.', 'Tomas needs Marcus''s urgent, formal approval to engage a contractor. Marcus is travelling abroad.', 'Face-to-face', 'Instant messaging', 'Social media', 'Email', 'Collaborative workspace', 'Document', 'Video conference', '', 'D', 'D, Email. Urgent but formal approval across geography needs a fast, traceable channel. Section 6.3.3, Section 5.3.1. ## Question 2', 'published', 15),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part A', 2, 'A', 'single', 'For each situation, select the categorisation and reason that best fit.', 'During Foundations, Bram complains that there is no full detailed specification of the Makers'' Wing upfront, fearing constant change and confusion.', 'Approach-based, because clarity of purpose is missing and prevents work from starting.', 'Approach-based, because Bram has not understood that AgilePM captures requirements at a high level and evolves detail iteratively.', 'VUCA-derived, because market shifts demand detailed definition.', 'VUCA-derived, because external pressures require flexible scope.', '', '', '', '', 'B', 'B. The issue is internal: Bram has not understood AgilePM''s high-level, iterative handling of requirements. That is an approach-based risk. Chapter 11.1, Section 2.4.2, Section 9.2.1.', 'published', 16),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part A', 2, 'A', 'single', 'For each situation, select the categorisation and reason that best fit.', 'New accessibility regulations take effect in six months and may force changes to the studio fit-out.', 'Approach-based, because earlier planning failed to track legislation.', 'Approach-based, because Greta should have monitored the law from the start.', 'VUCA-derived, because new legislation is an external factor requiring adaptation.', 'VUCA-derived, because internal compliance gaps cause uncertainty.', '', '', '', '', 'C', 'C. New legislation is external and unpredictable, so it is VUCA-derived. Chapter 11.1, Section 9.2.1.', 'published', 17),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part A', 2, 'A', 'single', 'For each situation, select the categorisation and reason that best fit.', 'At a Sprint Review, Dr Okafor finds that commercial retail has crept ahead of the community mission, drifting from the vision.', 'Approach-based, because the team failed to validate delivery against the vision continuously.', 'Approach-based, because the vision was not documented.', 'VUCA-derived, because customer expectations change unpredictably.', 'VUCA-derived, because agile welcomes change, so drift is normal.', '', '', '', '', 'A', 'A. Drift from the vision reflects a failure to validate delivery against it continuously, which is approach-based. Chapter 11.2, Section 6.1.1, Section 3.5.4.', 'published', 18),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part A', 2, 'A', 'single', 'For each situation, select the categorisation and reason that best fit.', 'Salvaged-material prices rise ten percent because of a market shortage, pushing the budget over.', 'Approach-based, because the estimates were not validated at Foundations.', 'Approach-based, because agile makes estimates vague.', 'VUCA-derived, because internal constraints stop the team adjusting.', 'VUCA-derived, because market price movements are external and could not be anticipated.', '', '', '', '', 'D', 'D. Market price movement is external and unforeseeable, so it is VUCA-derived. Chapter 11.1, Section 10.4.', 'published', 19),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part A', 2, 'A', 'single', 'For each situation, select the categorisation and reason that best fit.', 'Three months after opening, membership is below target. Visitors say they simply did not know the studios were available.', 'Approach-based, because realisation planning should have included communicating the offer.', 'VUCA-derived, because visitor preferences shift unpredictably.', 'VUCA-derived, because external uncertainty affects how people discover services.', 'Approach-based, because the Business Case was never approved.', '', '', '', '', 'A', 'A. The offer was not communicated. That is a realisation-planning gap, an approach-based risk. Chapter 11.2, Section 7.8.', 'published', 20),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part B', 2, 'B', 'single', '', 'It is the end of the Foundations Phase for Increment 4. Is this an appropriate time to review the Project Approach Questionnaire?', 'Yes. The PAQ is reviewed at the end of Foundations and whenever Foundations is revisited.', 'No. It is a one-off Feasibility activity.', 'No. The team is established, so views are unlikely to have changed.', 'Yes, because comprehensive documentation is what matters most.', '', '', '', '', 'A', 'A. The PAQ is reviewed at the end of Foundations and whenever Foundations is revisited. Chapter 11.2.', 'published', 21),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part B', 2, 'B', 'single', '', 'How should the review be conducted?', 'Each participant completes their own and sends it to Tomas.', 'One PAQ is completed as the output of a facilitated workshop attended by all participants.', 'Only the leadership roles complete it.', 'Each Team Leader completes one with their team.', '', '', '', '', 'B', 'B. A single PAQ is produced as the output of a facilitated workshop attended by all participants. Chapter 11.2, Appendix G.', 'published', 22),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part B', 2, 'B', 'single', '', 'The review shows one statement with a collective "Disagree" and another with a collective "Strongly Disagree". What should Tomas do?', 'Investigate only the "Strongly Disagree".', 'Investigate both, because any disagreement signals a risk to the approach that must be addressed.', 'Take no immediate action and stay aware.', 'Take no action, as only two of many statements are affected.', '', '', '', '', 'B', 'B. Any disagreement signals a risk to the approach and must be investigated, so both statements are addressed. Chapter 11.2.', 'published', 23),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part B', 2, 'B', 'single', '', 'The PAQ reveals that some Developers do not understand the combined AgilePM and Scrum approach. What tailoring action fits?', 'Proceed and trust they will learn on the job.', 'Replace them with people who already have the experience.', 'Arrange targeted AgilePM and Scrum training for the team.', 'Delay the project until everyone agrees.', '', '', '', '', 'C', 'C. The approach is tailored, not abandoned. Targeted training addresses the gap. Chapter 11.1, Chapter 11.2.', 'published', 24),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part B', 2, 'B', 'single', '', 'A specialist heritage contractor states, from a past bad experience, that they will not "work in an agile way". What is the most effective response?', 'Drop the contractor and find another.', 'Insist they adopt agile and offer to fund training.', 'Continue as normal and rely on the approach to absorb it.', 'Tailor the approach to accommodate their way of working while minimising the impact on the rest of the project.', '', '', '', '', 'D', 'D. AgilePM is tailored to context. Accommodate the partner''s way of working while limiting the impact elsewhere. Section 2.5.2, Chapter 11.2.', 'published', 25),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part C', 2, 'C', 'multi', '', 'Which 2 statements describe AgilePM''s approach to managing risk?', 'AgilePM removes all risk before execution.', 'Risk management is embedded in day-to-day activities and addressed at several levels.', 'Risk is the Project Manager''s sole responsibility.', 'The Product Owner may adjust Backlog priorities, with advice from the Solution Architect and Project Manager, to address risk.', 'Risk is handled only at Sprint Reviews.', '', '', '', 'B,D', 'B and D. Risk management is embedded and multi-level, and the Product Owner adjusts priorities with advice to address risk. Chapter 11.2, Section 9.2.1, Section 5.4.1.', 'published', 26),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part C', 2, 'C', 'multi', '', 'Which 2 statements describe behaviour that supports effective risk management?', 'Team members share responsibility for identifying and mitigating risk.', 'The Project Manager should own all risk alone.', 'Developers must resolve every risk without escalating.', 'The Solution Architect should handle all technical risk in isolation.', 'Risk management is proactive and part of daily activity, not a separate process.', '', '', '', 'A,E', 'A and E. Risk is a shared responsibility and is proactive, part of daily work. Chapter 11.2, Section 5.8, Section 2.4.2.', 'published', 27),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part C', 2, 'C', 'multi', '', 'At Sprint Planning the team spots a risk in integrating the booking platform with the membership system. Which 2 describe how to handle it within AgilePM?', 'Escalate at once to the Project Manager to devise a mitigation.', 'The Delivery Team addresses it collaboratively while keeping project-level roles informed.', 'The Project Manager tells the Solution Architect to resolve it alone.', 'The team escalates and pauses related work until it is resolved.', 'The Project Manager coordinates with the Solution Architect and Business Visionary to align the response with project priorities.', '', '', '', 'B,E', 'B and E. The Delivery Team resolves it collaboratively while keeping project roles informed, and the Project Manager aligns the response with priorities across roles. Sections 5.4.3, 5.3.4 and 5.3.3, Chapter 11.2.', 'published', 28),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part C', 2, 'C', 'multi', '', 'Nina, the Compliance Advisor, has very limited availability, which threatens the integrity of the increments. Which 2 actions fit?', 'Tomas coordinates a communication plan so the team has timely access to Nina''s expertise.', 'Escalate to Marcus to allocate more compliance resource.', 'Record the risk and delay all compliance-sensitive features until Nina is free.', 'Developers adapt how they communicate to make the most of Nina''s limited time.', 'The team proceeds on assumptions and reviews with Nina at the end of the increment.', '', '', '', 'A,D', 'A and D. Plan communication so the team gets timely access, and have the Developers adapt to make the most of limited availability. Sections 5.3.4 and 5.4.3, Section 6.1.2, Chapter 11.2.', 'published', 29),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 2, Part C', 2, 'C', 'multi', '', 'Which 2 statements correctly assign risk ownership in AgilePM?', 'The Project Manager owns all project risk.', 'The Solution Architect owns Solution Delivery risk.', 'The Product Owner owns all risk in the backlog.', 'The Project Manager owns Delivery Enablement risk, including organisation, schedule and dependencies.', 'Developers own all risk for their own work.', '', '', '', 'B,D', 'B and D. The Solution Architect owns Solution Delivery risk and the Project Manager owns Delivery Enablement risk. Chapter 11.1. ## Question 3', 'published', 30),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'A regenerated Harbour Quarter that blends heritage, community livelihoods and sustainable public arts.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'A', 'A, Vision Statement. The overall ambition and direction. Section 8.2.', 'published', 31),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'A fully operational Makers'' Wing offering bookable studio residencies.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'B', 'B, Product Goal. A medium-term product outcome. Section 8.2.', 'published', 32),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'As a visiting maker, I want to book a studio session online so that I can plan my visit.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'C', 'C, Product Backlog Item or User Story. Expressed in user-story form, describing value to a user. Section 8.2.', 'published', 33),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'Commission the studio utilities this Sprint so the first residencies can run.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'D', 'D, Sprint Goal. The single objective the Sprint rallies around. Section 3.5, Section 8.2.', 'published', 34),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'Draft the studio-residency booking confirmation email template.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'E', 'E, Sprint Backlog Item. A task-level activity contributing to the Sprint Goal. Section 8.2.', 'published', 35),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part A', 3, 'A', 'match', 'For each item in Column 1, select the AgilePM requirement type from Column 2. Each type may be used once, more than once, or not at all.', 'All public-facing features meet accessibility standards and pass safety sign-off.', 'Vision Statement', 'Product Goal', 'Product Backlog Item or User Story', 'Sprint Goal', 'Sprint Backlog Item', 'Definition of Done', '', '', 'F', 'F, Definition of Done. Cross-cutting quality and compliance criteria that apply to all work. Section 8.2.3.7.', 'published', 36),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part B', 3, 'B', 'single', '', 'Which one statement does NOT align with AgilePM''s MoSCoW prioritisation?', 'Must Haves are essential. Without them the solution is unviable.', 'Should Haves must be delivered for the project to be deemed successful.', 'Could Haves are delivered only if time and resources allow.', 'Won''t Have this time requirements are out of scope now but may return later.', '', '', '', '', 'B', 'B is the one that does NOT align. Should Haves are important but not vital. The solution remains viable without them. Only Must Haves are essential. Section 9.2.2.', 'published', 37),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part B', 3, 'B', 'single', '', 'When defining prioritisable Backlog items for a Product Goal, which action is appropriate?', 'Break the goal into smaller items, each justified by the value it adds.', 'Create an item for every conceivable task so nothing is missed.', 'Prioritise purely on the cost of building each feature.', 'Defer all prioritisation to Sprint Planning.', '', '', '', '', 'A', 'A. Break the Product Goal into smaller items, each justified by value, to keep traceability to the business need. Section 9.2.1, Section 5.4.1.', 'published', 38),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part B', 3, 'B', 'single', '', 'To be safe, the team proposes classing every Increment 4 requirement as a Must Have. Is this appropriate?', 'Yes. It ensures nothing critical is missed.', 'Yes. It guarantees the goal is met.', 'No. Classing everything as Must removes contingency and undermines timeboxing.', 'No. Must Haves should have been dealt with in earlier Increments.', '', '', '', '', 'C', 'C. Making everything a Must Have removes contingency and undermines timeboxing. Must Haves should stay near sixty percent of effort. Sections 9.2.1 and 9.8.', 'published', 39),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part B', 3, 'B', 'single', '', 'Towards the end of Sprint 5, the team fully documents the studio layout and adds it to the Sprint 6 Backlog, where the goal is to fit out the studios. Is this timing appropriate?', 'Yes. This is the last responsible moment to define that detail.', 'Yes. All such detail should be fixed at Foundations.', 'No. The detail should emerge only during the Sprint that builds it.', 'No. The Delivery Team alone should design it without documenting it.', '', '', '', '', 'A', 'A. Defining the detail just before the Sprint that delivers it is the last responsible moment. Section 8.2.4, Section 4.3.6. Tempting distractor: C. AgilePM does favour emergent detail, but documenting it for the Sprint about to build it is the responsible point, not a fault.', 'published', 40),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part B', 3, 'B', 'single', '', 'As the Increment progresses, Aisha and Dr Okafor adjust the MoSCoW priorities to protect value delivery. Is this appropriate?', 'Yes. Revisiting priorities keeps the work aligned with evolving business need.', 'Yes, but only the Project Manager may change priorities.', 'No. Changing priorities mid-Increment reduces commitment.', 'No. MoSCoW is set once at Foundations and then fixed.', '', '', '', '', 'A', 'A. Priorities are revisited regularly to stay aligned with evolving business need. Section 10.3.2, Section 9.5.', 'published', 41),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part C', 3, 'C', 'multi', '', 'Early in the Increment the team used T-shirt sizing for rough estimates. Which 2 statements explain why this was appropriate?', 'T-shirt sizing is quick and suits early estimates made from limited information.', 'T-shirt sizing is precise enough for detailed planning.', 'It supports initial planning and prioritising the Foundations work.', 'It removes the need for any later refinement.', 'It gives every team member a full understanding of requirements from the start.', '', '', '', 'A,C', 'A and C. T-shirt sizing is quick under limited information and supports early planning and prioritisation. Section 8.3.5, Section 10.2.2.', 'published', 42),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part C', 3, 'C', 'multi', '', 'T-shirt sizing is estimating by analogy. Which 2 statements explain why analogy suits this stage?', 'It needs detailed breakdowns.', 'It is quick and effective when detail is limited.', 'It draws on past experience for rough estimates.', 'It is always highly accurate.', 'It lets estimators ignore the context of the current project.', '', '', '', 'B,C', 'B and C. Analogy is quick when detail is limited and draws on past experience. Section 8.3.5.', 'published', 43),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part C', 3, 'C', 'multi', '', 'The team then used Planning Poker to refine the estimates. Which 2 statements explain its value?', 'It is quick but lacks the precision needed.', 'It blocks collaboration.', 'It lets members of differing experience contribute.', 'It builds group consensus, making estimates more reliable.', 'It adds nothing, being another analogy method.', '', '', '', 'C,D', 'C and D. Planning Poker lets people of differing experience contribute and builds consensus, improving reliability. Section 10.2.2, Section 5.4.3.', 'published', 44),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 3, Part C', 3, 'C', 'multi', '', 'Tomas needs to work out how many Sprints the studios will take, from the Planning Poker estimates. Which 2 actions fit AgilePM?', 'Use commitment-based planning to judge how many story points fit in a Sprint, establishing velocity.', 'Convert story points into person-days to size the schedule.', 'Assign equal workloads to every Sprint.', 'Treat story points as relative effort and avoid converting them to days.', 'Re-estimate using a time-based technique instead.', '', '', '', 'A,D', 'A and D. Use commitment-based planning to establish velocity, and treat story points as relative effort rather than converting them to days. Section 10.2.2, Section 4.3.8. ## Question 4', 'published', 45),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part A', 4, 'A', 'single', '', 'Midway through the Increment a rival venue opens nearby, threatening projected income. Which artifact supports financial governance here, and why?', 'Business Case, because it is kept current so the project stays justified and aligned to goals.', 'Feasibility Assessment, because it is reused throughout every phase.', 'Solution Architecture Definition, because it holds the financial modelling.', 'Solution Backlog, because it manages the list of features.', '', '', '', '', 'A', 'A. The Business Case is kept current so the project stays justified and aligned. Chapter 12.3, Section 7.5.2.1.', 'published', 46),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part A', 4, 'A', 'single', '', 'At the end of Foundations, Greta is asked for an overall cost estimate for the studio build. What form should it take?', 'A single precise figure that is easy to report against Sprint by Sprint.', 'A ranged estimate that reflects the uncertainty of high-level Foundations descriptions.', 'A statement that no estimate is possible yet.', 'An estimate with contingency that guarantees the Minimum Useable Subset.', '', '', '', '', 'B', 'B. A ranged estimate reflects the uncertainty of high-level Foundations descriptions. Section 8.3.5, Chapter 12.3.1.', 'published', 47),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part A', 4, 'A', 'single', '', 'Marcus must justify continuing the project to the board, who know the market has shifted. What best reassures them on viability?', 'The Feasibility-phase Business Case still holds for the whole project.', 'Present the revised Foundations Summary and hand out the source document.', 'As Business Sponsor, Marcus owns the Business Case and is accountable for its ongoing viability, which he reassesses.', 'Invite the board to a Sprint Review to judge progress for themselves.', '', '', '', '', 'C', 'C. The Business Sponsor owns the Business Case and is accountable for ongoing viability. Section 5.3.1.', 'published', 48),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part A', 4, 'A', 'single', '', 'As the first studios go into use, which of the following would NOT typically be required for financial governance at deployment?', 'A Benefits Assessment of how benefits should now accrue.', 'An analysis of actual costs against the Foundations estimates.', 'An assessment of the impact of features that were expected but not delivered.', 'The originally approved Delivery Plan with Sprint-by-Sprint expenditure deviations.', '', '', '', '', 'D', 'D is the one NOT required. Deployment governance needs a Benefits Assessment, actual against estimated cost, and the impact of undelivered features. The original Delivery Plan is a planning artifact, not a governance one. Chapter 12.3, Section 7.5.2.6.', 'published', 49),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part A', 4, 'A', 'single', '', 'Nina wants an auditable record of the technical and design decisions that show how compliance was built into the solution. Which artifact best provides this?', 'The Management Approach Definition.', 'The Project Review Report.', 'The Sprint Review Records.', 'The Solution Architecture Definition, as it records the technical and compliance design decisions as an auditable trail.', '', '', '', '', 'D', 'D. The Solution Architecture Definition records the technical and compliance design decisions as an auditable trail. Chapter 12.2. Note: if the question instead asked for evidence that compliance was met during delivery, the answer would shift to Sprint Review Records. The cue here is design decisions, which point to the Solution Architecture Definition.', 'published', 50),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part B', 4, 'B', 'single', '', 'Tomas convenes a Project Sprint Planning event. Is it appropriate for the Team Leaders to attend?', 'Yes, because AgilePM mandates joint decision-making.', 'Yes, because they give real-time input on progress, risk and dependencies.', 'No, because they should focus on development work.', 'No, because leaders plan and inform them afterwards.', '', '', '', '', 'B', 'B. Team Leaders give real-time input on progress, risk and dependencies, which makes planning realistic. Sections 10.2.2 and 10.2.3.', 'published', 51),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part B', 4, 'B', 'single', '', 'A rooftop planting scheme, a Should Have, is delayed. Greta suggests a workaround and reclassifying it as Won''t Have this time. Is this appropriate?', 'Yes. Should Haves are contingency and may be deferred with a workaround to protect the Must Haves.', 'Yes. Any unresolved dependency justifies removing a requirement.', 'No. A Should Have must never be removed.', 'No. Workarounds undermine the Business Case.', '', '', '', '', 'A', 'A. Should Haves are the first contingency and may be deferred with a temporary workaround to protect the Must Haves. Section 9.2.2, Section 9.5.', 'published', 52),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part B', 4, 'B', 'single', '', 'Marcus worries the delays mean lots of effort but no visible progress. Should Tomas switch the progress reports to show effort expended instead of delivered features?', 'Yes. Tracking effort gives transparency.', 'Yes. AgilePM values workload tracking.', 'No. Effort-based reporting measures value rather than time.', 'No. Effort-based reporting misleads stakeholders about real progress.', '', '', '', '', 'D', 'D. Progress is measured by delivered value, not effort. Effort-based reporting misleads on real progress. Section 10.4.1. Tempting distractor: C is also a "No", but it misstates what effort measures, so it is wrong.', 'published', 53),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part B', 4, 'B', 'single', '', 'Tomas decides, on his own, to re-sequence the Delivery Plan to build the studios first for early testing. Is this appropriate?', 'Yes. The Delivery Plan should adapt to real conditions.', 'Yes. All sequencing changes belong in the Delivery Plan.', 'No. The Delivery Plan is fixed after Foundations.', 'No. Sequencing should be agreed collaboratively, not decided by the Project Manager alone.', '', '', '', '', 'D', 'D. Sequencing is a collaborative decision, not the Project Manager''s alone. Section 10.2.3.', 'published', 54),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part B', 4, 'B', 'single', '', 'Aisha tells Marcus that keeping the programme aligned to visitor needs after opening will be handled by the Delivery Team in the final Sprint. Is this aligned with AgilePM?', 'Yes. Delivery Teams should focus on delivery until the final Sprint.', 'Yes. Realisation can reasonably wait until the final Sprint.', 'No. Realisation is the Business Visionary''s responsibility, not the Delivery Team''s.', 'No. Realisation must be fully fixed in the Business Case before development.', '', '', '', '', 'C', 'C. Realisation is owned by the Business Visionary, supported by the Sponsor and Advisors, not by the Delivery Team. Section 5.3.2, Section 7.8.', 'published', 55),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part C', 4, 'C', 'multi', '', 'Which 2 actions align with the AgilePM approach to managing dependencies across the two teams?', 'A formal approval process for all Backlog changes.', 'A dedicated Dependency Coordinator who approves all cross-team work.', 'A cross-team Scrum of Scrums every few days to surface and escalate dependencies.', 'A weekly written progress report from each team.', 'A shared Team Board giving real-time visibility of dependencies and progress.', '', '', '', 'C,E', 'C and E. A Scrum of Scrums every few days surfaces dependencies, and a shared Team Board gives real-time visibility. Section 10.2.3, Section 4.3.8.', 'published', 56),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part C', 4, 'C', 'multi', '', 'Marcus finds the reports thin and Bram dislikes attending meetings. Which 2 actions would help?', 'Share an end-of-Sprint walk-around video to give Marcus a visual update.', 'Let Bram check in informally whenever it suits him.', 'Add monthly update meetings for both.', 'Give Marcus a detailed weekly written report instead of a per-Sprint update.', 'Have Bram attend Sprint Reviews to see completed work first-hand.', '', '', '', 'A,E', 'A and E. A walk-around video shows visible progress, and attending Sprint Reviews lets Bram see completed work first-hand. Sections 4.3.7 and 4.3.8, Section 10.2.3.7.', 'published', 57),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part C', 4, 'C', 'multi', '', 'Aisha finds gaps between what she asked for and what the teams delivered. Which 2 actions should she take in the next Sprint?', 'Increase her availability for discussion, reviews and feedback.', 'Define clear acceptance criteria with practical examples for Backlog items.', 'Require detailed design documents for every item before development.', 'Assign a Business Analyst to translate items into structured requirements.', 'Standardise estimation with Planning Poker for predictability.', '', '', '', 'A,B', 'A and B. Greater Product Owner availability and clear acceptance criteria with examples close the gap between intent and delivery. Section 5.4.1, Section 8.2.3.', 'published', 58),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part C', 4, 'C', 'multi', '', 'Integration issues emerge between the studios'' power and ventilation systems, drawing more energy than planned. Which 2 actions align with AgilePM risk guidance?', 'Extend the Sprint to resolve the integration.', 'Document the risks and have Greta decide the mitigations alone.', 'Add integration testing to the acceptance criteria for the relevant items.', 'Include explicit integration test scenarios in the Sprint Backlog.', 'Schedule integration workshops only at the end of all the Sprints.', '', '', '', 'C,D', 'C and D. Build integration testing into the acceptance criteria and the Sprint Backlog so risk is handled within the Sprint. Section 8.2.3, Section 11.2.', 'published', 59),
  ('0a052eda-f115-4e08-bb3b-10c6edf8d20e', 'Question 4, Part C', 4, 'C', 'multi', '', 'A sister project elsewhere suffered serious quality failures, and stakeholders are anxious. Which 2 actions would best reassure them?', 'Tell stakeholders that AgilePM prevents quality issues through iterative delivery.', 'Define and make visible the quality criteria, with the team confirming compliance before declaring an item Done.', 'Engage stakeholders only through written assurances.', 'Appoint an independent Quality Manager to approve all work before release.', 'Review the sister project''s issues with stakeholders and show how this project addresses them differently.', '', '', '', 'B,E', 'B and E. Make quality criteria visible with the team confirming before Done, and review the sister project''s failures to show how this project addresses them. Section 8.2.3.7, Chapter 11.2. Tempting distractor: A sounds reasonable but is one-way assurance, which AgilePM treats as weaker than visible quality and engagement.', 'published', 60);
