#!/usr/bin/env node
// The board's reference pages and icons, lifted out of the design file and into the game.
//
// `docs/scrum-board/scrum-big-picture.html` is the design source: one file, no build step, and the
// place the layout and the icon drawing code are decided. What it is NOT, any more, is the source
// of truth for the WORDS. The game's teaching copy is editable from the live page - defaults in
// code, overrides in `zoo_copy` - and a trainer polishing a sentence at 9pm must not need a
// developer, nor a second copy of the Scrum Guide to keep in step.
//
// So the words come across once, mechanically, and live here afterwards. Hand-copying 28 pages of
// Guide-derived text would have been a tenth source of one truth in this codebase, and the park's
// own notes record nine.
//
//   node scripts/scrumBoard/import.mjs
//   node scripts/scrumBoard/import.mjs --check   (fails if the generated files are stale)

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const SRC = resolve(ROOT, 'docs/scrum-board');
const OUT = resolve(ROOT, 'src/components/zooGame/board');
const check = process.argv.includes('--check');

/** The knowledge pages, read out of the design file's own `P` array. */
function pages() {
  const html = readFileSync(resolve(SRC, 'scrum-big-picture.html'), 'utf8');
  const from = html.indexOf('const P=[');
  if (from < 0) throw new Error('the design file has no P array - has it been restructured?');
  const body = html.slice(from);
  const to = body.indexOf('\n];');
  if (to < 0) throw new Error('the P array does not end where expected');
  // Our own file, read at build time, never at runtime.
  // eslint-disable-next-line no-eval
  const read = eval(`(${body.slice('const P='.length, to + 2)})`);
  if (!Array.isArray(read) || !read.length) throw new Error('the P array came back empty');
  return read;
}

/** Every icon, as the markup inside its <svg> plus the box it is drawn in. */
function icons() {
  const dir = resolve(SRC, 'icons');
  return readdirSync(dir).filter((f) => f.endsWith('.svg')).sort().map((f) => {
    const svg = readFileSync(resolve(dir, f), 'utf8');
    const box = svg.match(/viewBox="([^"]+)"/)?.[1];
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
    if (!box) throw new Error(`${f} has no viewBox`);
    return { id: basename(f, '.svg'), box, inner };
  });
}

const banner = `// Generated by scripts/scrumBoard/import.mjs from docs/scrum-board. Do not edit by hand.
//
// The WORDS here are the shipped defaults only. They are editable in the game from the live page,
// through the copy editor, and an override lives in \`zoo_copy\` rather than in this file - so
// re-running the import never overwrites anybody's edit.
`;

const q = (s) => JSON.stringify(s);

function writePages(P) {
  const body = P.map((p) => `  {
    id: ${q(p.id)},
    kind: ${q(p.kind ?? '')},
    title: ${q(p.title)},
    lede: ${q(p.lede ?? '')},
    facts: [${(p.facts ?? []).map(([a, b]) => `[${q(a)}, ${q(b)}]`).join(', ')}],
    secs: [
${(p.secs ?? []).map(([h, b]) => `      [${q(h)},\n        ${q(b)}],`).join('\n')}
    ],
    rel: [${(p.rel ?? []).map(q).join(', ')}],
  },`).join('\n');
  return `${banner}
/** One reference page behind an icon on the board. */
export interface BoardPage {
  /** Stable id. It is the anchor the cross-links in \`secs\` point at, and the copy key's stem. */
  id: string;
  /** Foundation, Event, Accountability, Artifact, Commitment - the band it belongs to. */
  kind: string;
  title: string;
  /** The one-sentence answer, before any detail. */
  lede: string;
  /** Short label-and-value pairs, shown as a strip. */
  facts: [string, string][];
  /** Heading and body. The body is HTML and is sanitised on render, because it is editable. */
  secs: [string, string][];
  /** Other pages worth reading next. */
  rel: string[];
}

export const BOARD_PAGES: BoardPage[] = [
${body}
];

export const pageById = (id: string): BoardPage | undefined => BOARD_PAGES.find((p) => p.id === id);
`;
}

function writeIcons(list) {
  return `${banner}
/** An icon from the board, as the markup inside its <svg> and the box it is drawn in. */
export interface BoardIcon { box: string; inner: string }

export const BOARD_ICONS: Record<string, BoardIcon> = {
${list.map((i) => `  ${q(i.id)}: { box: ${q(i.box)}, inner: ${q(i.inner)} },`).join('\n')}
};

export type BoardIconName = keyof typeof BOARD_ICONS;
`;
}

const P = pages();
const I = icons();
const want = [
  [resolve(OUT, 'boardPages.ts'), writePages(P)],
  [resolve(OUT, 'boardIcons.ts'), writeIcons(I)],
];

let stale = 0;
for (const [path, text] of want) {
  let now = null;
  try { now = readFileSync(path, 'utf8'); } catch { /* not written yet */ }
  if (now === text) continue;
  stale += 1;
  if (check) { console.error(`stale: ${path.replace(`${ROOT}/`, '')}`); continue; }
  writeFileSync(path, text);
  console.log(`wrote ${path.replace(`${ROOT}/`, '')}`);
}

if (check && stale) {
  console.error(`\n${stale} generated file(s) do not match docs/scrum-board.\nRun: node scripts/scrumBoard/import.mjs`);
  process.exit(1);
}
console.log(`${P.length} pages, ${I.length} icons${check ? ' - in step' : ''}`);
