import { Helmet } from 'react-helmet-async';
import { SITE_URL } from '@/config/featureFlags';
import { useCompanyName } from '@/hooks/useCompanyName';

interface SEOHeadProps {
  /** What this page is, without the company name: "Impact Map Builder", not
   *  "Impact Map Builder - Altogether Agile". The company name is appended from site_settings,
   *  because twenty-five pages spelling it out is twenty-five pages that say the wrong thing on
   *  somebody else's site. */
  title: string;
  /** Set for a title that must stand alone, with no company name after it. */
  standalone?: boolean;
  description: string;
  /** Path for canonical + og:url, e.g. "/events". Defaults to "/". */
  path?: string;
  /** Absolute or root-relative image URL. Defaults to the site OG image. */
  image?: string;
  /** og:type. Defaults to "website". */
  type?: 'website' | 'article';
  /** Optional shorter OG/Twitter description (falls back to description). */
  ogDescription?: string;
}

/**
 * Shared <head> meta for pages: title, description, canonical, Open Graph and
 * Twitter cards. Dedupes the near-identical Helmet blocks across pages.
 *
 * NOTE: this only affects the client-rendered head. Crawler-facing meta for
 * prerendered routes is generated by scripts/prerender.mjs (the source of
 * truth for Google) — keep the two in sync when changing a page's meta.
 */
export function SEOHead({ title, description, path = '/', image, type = 'website', ogDescription, standalone = false }: SEOHeadProps) {
  const companyName = useCompanyName();
  const fullTitle = standalone || title.includes(companyName) ? title : `${title} - ${companyName}`;
  const url = `${SITE_URL}${path === '/' ? '/' : path}`;
  const img = image
    ? (image.startsWith('http') ? image : `${SITE_URL}${image}`)
    : `${SITE_URL}/og-image.png`;
  const ogDesc = ogDescription || description;

  return (
    <Helmet>
      <title>{fullTitle}</title>
      <meta name="description" content={description} />
      <link rel="canonical" href={url} />
      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={ogDesc} />
      <meta property="og:type" content={type} />
      <meta property="og:image" content={img} />
      <meta property="og:url" content={url} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={ogDesc} />
      <meta name="twitter:image" content={img} />
    </Helmet>
  );
}
