/* Generated by scripts/extract-building-art.mjs - do not edit by hand. */

/** The building kinds that have a drawing of their own.
 *
 *  A tile is a picture and cannot be repainted, so a building drawn from one wears the colours it
 *  was drawn in and the studio does not offer to change them. Kinds absent from this list are built
 *  out of coloured boxes and do wear what they are given.
 *
 *  Names only: the tiles themselves are in buildingArt.generated.ts, which is imported by the view
 *  that draws them and nowhere else.
 */
export const TILED_BUILDINGS: readonly string[] = ['cafe', 'kiosk', 'shop', 'toilets'];
