#!/usr/bin/env node
// The build strip's icons, from docs/zoo-toolbar/icons into the game.
//
// Same shape as scripts/scrumBoard/import.mjs and for the same reason: the drawings are made
// outside the repo and handed over as files, so they are kept as files and the TypeScript is
// generated from them. Re-running this is how a new set is taken; `--check` is how CI notices that
// somebody edited the generated file instead.
//
// The ONE thing this does differently to the board importer is colour. The board's icons are
// illustrations and keep the brand palette, tokenised to CSS variables. These are controls: they
// have to be the colour of the button they sit on, which is grey at rest, darker under the pointer
// and orange while the menu is open. So the single brand hex the drawings use becomes
// `currentColor` and the button decides.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SRC = resolve(ROOT, 'docs/zoo-toolbar/icons');
const OUT = resolve(ROOT, 'src/components/zooGame/toolbarIcons.ts');
const check = process.argv.includes('--check');

/** The deep teal every drawing in the set is made of. */
const INK = /#004D4D/gi;

const q = (s) => JSON.stringify(s);

/** Every icon, as the markup inside its <svg> plus the box it is drawn in. */
function icons() {
  const files = readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();
  if (!files.length) throw new Error(`no .svg files in ${SRC}`);
  return files.map((f) => {
    const svg = readFileSync(resolve(SRC, f), 'utf8');
    const box = svg.match(/viewBox="([^"]+)"/)?.[1];
    if (!box) throw new Error(`${f} has no viewBox`);
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
    if (!inner) throw new Error(`${f} has nothing inside its <svg>`);
    // Said out loud rather than quietly tolerated. A drawing with a second colour in it would come
    // through with that colour baked in and sit there grey while the button around it turned
    // orange - a fault that only shows up in one state, long after the import.
    const left = inner.replace(INK, '').match(/#[0-9a-f]{3,8}\b/i);
    if (left) throw new Error(`${f} uses ${left[0]} as well as the ink colour - see docs/zoo-toolbar/README.md`);
    // Ids match the ids used in the game, which are kebab-case: 'lives-in', 'on-the-park'.
    return { id: basename(f, '.svg').replace(/_/g, '-'), inner: inner.replace(INK, 'currentColor'), box };
  });
}

const I = icons();
const text = `// Generated by scripts/zooToolbar/import.mjs from docs/zoo-toolbar/icons. Do not edit by hand.
//
// One drawing per NAME on the build strip, not per group: four groups are called Look and share
// this one Look. Which group gets which is in buildGroups.ts, beside the rest of what a group
// declares about itself.
//
// The ink is \`currentColor\`, so an icon is whatever colour its button's text is: grey at rest,
// darker under the pointer, orange while its menu is open. Nothing here picks a colour.

/** An icon for the build strip, as the markup inside its <svg> and the box it is drawn in. */
export interface ToolbarIcon { box: string; inner: string }

export const TOOLBAR_ICONS = {
${I.map((i) => `  ${q(i.id)}: { box: ${q(i.box)}, inner: ${q(i.inner)} },`).join('\n')}
} as const satisfies Record<string, ToolbarIcon>;

export type ToolbarIconName = keyof typeof TOOLBAR_ICONS;
`;

let now = null;
try { now = readFileSync(OUT, 'utf8'); } catch { /* not written yet */ }
const rel = OUT.replace(`${ROOT}/`, '');
if (now === text) {
  console.log(`${I.length} icons - in step`);
} else if (check) {
  console.error(`stale: ${rel}\n\n${rel} does not match docs/zoo-toolbar/icons.\nRun: node scripts/zooToolbar/import.mjs`);
  process.exit(1);
} else {
  writeFileSync(OUT, text);
  console.log(`${I.length} icons -> ${rel}`);
}
