#!/usr/bin/env node
/**
 * Cuts isometric props - fences, trees, benches, visitors - out of a licensed scene illustration
 * and writes them as a TypeScript module the showcase view can render.
 *
 * The sheets arrive as a whole composed park rather than a tidy row of items, so the useful pieces
 * are scattered through a hundred-odd top-level groups. See scripts/lib/svg-sheet.mjs for how they
 * are found and measured.
 *
 * A prop listed with `tint` has its flat colours swapped for numbered slots, so the game can
 * recolour it - a fence wears the colour of the zone it encloses rather than the colour the
 * illustrator happened to pick.
 *
 * Hand-run, like the animals; the output is committed.
 *
 *   npm run iso-art -- --index    numbered contact sheet of every group in the sheet
 *   npm run iso-art               write src/components/zooGame/art/isoArt.generated.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { chromium } from 'playwright';
import { topLevelGroups, measureGroups, slim, viewBoxOf, contactSheet } from './lib/svg-sheet.mjs';

const CONFIG = 'scripts/iso-art.config.json';
const OUT = 'src/components/zooGame/art/isoArt.generated.ts';
const SHEET = 'art-src/zoo/iso-contact-sheet.png';

const config = JSON.parse(readFileSync(CONFIG, 'utf8'));
const wantIndex = process.argv.includes('--index');
const browser = await chromium.launch();

const entries = [];
const credits = new Set();

for (const source of config.sources) {
  const svg = readFileSync(resolve(source.file), 'utf8');
  const groups = topLevelGroups(svg);
  const boxes = await measureGroups(browser, svg);
  if (boxes.length !== groups.length) {
    console.error(`${source.file}: ${groups.length} groups in the text, ${boxes.length} when rendered.`);
    process.exit(1);
  }

  if (wantIndex) {
    mkdirSync(dirname(SHEET), { recursive: true });
    await contactSheet(browser, groups, boxes, SHEET);
    console.log(`${source.file}: ${groups.length} groups -> ${SHEET}`);
    continue;
  }

  if (source.credit) credits.add(source.credit);
  for (const [name, spec] of Object.entries(source.props)) {
    const b = boxes[spec.group];
    if (!b) { console.error(`${name}: no group ${spec.group} in ${source.file}`); process.exit(1); }
    let body = slim(groups[spec.group]);
    // A drawing that leans on <use> and a clipPath id cannot be lifted out of its sheet: the same
    // prop drawn twice on a page would have two elements claiming the same id, and one of them
    // would win. Better to know here than to wonder why one bench is clipped to another's shape.
    if (/<use\b|<clipPath\b/i.test(body)) {
      console.error(`${name}: uses <use>/<clipPath>, which will not survive being cut out. Pick another drawing.`);
      process.exit(1);
    }
    // A tinted prop keeps its shading but gives up its hue: each colour becomes a numbered slot,
    // darkest last, so whoever renders it can hand in a ramp of their own.
    if (spec.tint) {
      spec.tint.forEach((hex, i) => {
        const before = body;
        body = body.split(hex).join(`#__T${i}__`).split(hex.toLowerCase()).join(`#__T${i}__`);
        if (before === body) { console.error(`${name}: tint colour ${hex} is not in the drawing`); process.exit(1); }
      });
      if (/#[0-9A-Fa-f]{6}/.test(body.replace(/#__T\d+__/g, ''))) {
        const left = [...new Set(body.replace(/#__T\d+__/g, '').match(/#[0-9A-Fa-f]{6}/g) ?? [])];
        console.error(`${name}: colours left untinted: ${left.join(' ')}`);
        process.exit(1);
      }
    }
    entries.push({ name, w: b.w, h: b.h, viewBox: viewBoxOf(b), tint: spec.tint?.length ?? 0, body });
  }
}

await browser.close();
if (wantIndex) process.exit(0);

entries.sort((a, b) => a.name.localeCompare(b.name));
const body = entries.map((e) => `  ${e.name}: {
    viewBox: '${e.viewBox}',
    w: ${e.w}, h: ${e.h},${e.tint ? `\n    tint: ${e.tint},` : ''}
    body: ${JSON.stringify(e.body)},
  },`).join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `/* Generated by scripts/extract-iso-art.mjs - do not edit by hand.
 *
 * Artwork: ${[...credits].join(', ')}, used under licence. Re-run \`npm run iso-art\` after changing
 * scripts/iso-art.config.json or the sheets in art-src/.
 *
 * All of it is drawn on one isometric grid, so a fence run and a tree and a visitor sit together
 * without any per-prop fiddling.
 */

export type IsoProp = {
  /** The prop's own box in the sheet, cropped tight. */
  viewBox: string;
  /** Size in sheet units - the same units for every prop here. */
  w: number;
  h: number;
  /** How many recolourable slots the drawing has, lightest first. Absent means fixed colours. */
  tint?: number;
  /** The SVG markup, with no wrapping <svg>. Tinted props carry #__T0__ style placeholders. */
  body: string;
};

export const ISO_ART: Record<string, IsoProp> = {
${body}
};
`);

console.log(`${entries.length} props -> ${OUT} (${(Buffer.byteLength(readFileSync(OUT)) / 1024).toFixed(0)} KB)`);
for (const e of entries) console.log(`  ${e.name.padEnd(15)} ${String(Math.round(e.w)).padStart(4)}×${String(Math.round(e.h)).padEnd(4)} ${(e.body.length / 1024).toFixed(1)} KB${e.tint ? `  ${e.tint} tint slots` : ''}`);
