// Generated by scripts/scrumBoard/import.mjs from docs/scrum-board. Do not edit by hand.
//
// The WORDS here are the shipped defaults only. They are editable in the game from the live page,
// through the copy editor, and an override lives in `zoo_copy` rather than in this file - so
// re-running the import never overwrites anybody's edit.

import type { BoardChip } from './boardLabels';

export declare function drawBoard(text: {
  INPUTS: BoardChip[][];
  OUTPUTS: BoardChip[][];
  DESC: [string, string][];
}): { svg: string; height: number };
