// Generated by scripts/scrumBoard/import.mjs from docs/scrum-board. Do not edit by hand.
//
// The WORDS here are the shipped defaults only. They are editable in the game from the live page,
// through the copy editor, and an override lives in `zoo_copy` rather than in this file - so
// re-running the import never overwrites anybody's edit.

/** One chip on the board: an icon with its name, or a dashed note. */
export interface BoardChip { t: string; k: string; id: string }

/** What each event inspects, laid out per column. */
export const BOARD_INPUTS: BoardChip[][] = [
  [
    {
      "t": "Product Backlog|Goal + PBIs",
      "k": "pb",
      "id": "product-backlog"
    },
    {
      "t": "Past Performance & Capacity",
      "k": "perf",
      "id": "topic-what"
    },
    {
      "t": "Definition|of Done",
      "k": "dod",
      "id": "definition-of-done"
    },
    {
      "t": "Increment",
      "k": "inc",
      "id": "increment"
    },
    {
      "t": "Improvements|from the last Retrospective",
      "k": "imp",
      "id": "sprint-retrospective"
    }
  ],
  [
    {
      "t": "Sprint Backlog|Sprint Goal + Plan",
      "k": "sb",
      "id": "sprint-backlog"
    }
  ],
  [
    {
      "t": "Increment",
      "k": "inc",
      "id": "increment"
    },
    {
      "t": "Sprint Goal",
      "k": "sg",
      "id": "sprint-goal"
    },
    {
      "t": "Product Goal",
      "k": "pg",
      "id": "product-goal"
    },
    {
      "t": "Product Backlog",
      "k": "pb",
      "id": "product-backlog"
    },
    {
      "t": "Changes in the Environment",
      "k": "env",
      "id": "sprint-review"
    }
  ],
  [
    {
      "t": "How the Sprint Went|individuals, interactions, processes, tools",
      "k": "how",
      "id": "sprint-retrospective"
    },
    {
      "t": "Definition|of Done",
      "k": "dod",
      "id": "definition-of-done"
    }
  ]
];

/** What each event adapts or creates. */
export const BOARD_OUTPUTS: BoardChip[][] = [
  [
    {
      "t": "Sprint Backlog|Goal, PBIs, Plan",
      "k": "sb",
      "id": "sprint-backlog"
    },
    {
      "t": "Product Backlog|refined",
      "k": "pb",
      "id": "product-backlog"
    }
  ],
  [
    {
      "t": "Sprint Backlog|adapted plan for the next 24 hours",
      "k": "sb",
      "id": "sprint-backlog"
    }
  ],
  [
    {
      "t": "Product Backlog|adapted",
      "k": "pb",
      "id": "product-backlog"
    }
  ],
  [
    {
      "t": "Improvements|actionable, for the next Sprint",
      "k": "imp",
      "id": "sprint-retrospective"
    },
    {
      "t": "Definition of|Done, if adapted",
      "k": "dod",
      "id": "definition-of-done"
    }
  ]
];

/** The two lines under each event: what it inspects, and what it adapts. */
export const BOARD_DESC: [string, string][] = [
  [
    "Inspect the Product Backlog",
    "Create the Sprint Backlog"
  ],
  [
    "Inspect progress toward the Sprint Goal",
    "Adapt the Sprint Backlog"
  ],
  [
    "Inspect the Sprint outcome",
    "Adapt the Product Backlog"
  ],
  [
    "Inspect how the Sprint went",
    "Adapt ways of working"
  ]
];
