INSERT INTO backlog_items (project_id, title, description, priority, status, backlog_position, estimated_value, estimated_effort, source, tags)
VALUES 
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Browse recipe catalog', 'As a user, I want to browse a catalog of recipes so that I can discover new meal ideas', 'High', 'New', 0, 8, 5, 'Product Owner', ARRAY['discovery', 'recipes']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Search recipes by ingredient', 'As a user, I want to search for recipes by ingredients I have so that I can reduce food waste', 'High', 'New', 1, 8, 5, 'User Research', ARRAY['search', 'ingredients']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Save favorite recipes', 'As a user, I want to save recipes to my favorites so that I can quickly find them later', 'High', 'New', 2, 5, 3, 'User Research', ARRAY['favorites', 'user-profile']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Create weekly meal plan', 'As a user, I want to create a weekly meal plan so that I can organize my meals in advance', 'High', 'New', 3, 13, 8, 'Product Owner', ARRAY['meal-planning', 'calendar']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Generate shopping list', 'As a user, I want to generate a shopping list from my meal plan so that I know what to buy', 'High', 'New', 4, 8, 5, 'User Research', ARRAY['shopping', 'automation']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Filter recipes by dietary needs', 'As a user, I want to filter recipes by dietary restrictions (vegan, gluten-free, etc.) so that I can find suitable meals', 'Medium', 'New', 5, 5, 5, 'User Research', ARRAY['filters', 'dietary']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'View nutritional information', 'As a user, I want to see nutritional information for each recipe so that I can track my diet', 'Medium', 'New', 6, 5, 5, 'Stakeholder', ARRAY['nutrition', 'health']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Share recipes with friends', 'As a user, I want to share recipes with friends so that we can exchange meal ideas', 'Medium', 'New', 7, 3, 3, 'User Research', ARRAY['social', 'sharing']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Rate and review recipes', 'As a user, I want to rate and review recipes so that I can help others find great meals', 'Low', 'New', 8, 3, 3, 'Community Feedback', ARRAY['reviews', 'community']),
  ('0c63447d-9f36-408e-a00b-367d956b7ded', 'Import recipes from URL', 'As a user, I want to import recipes from external websites so that I can consolidate all my recipes', 'Low', 'New', 9, 5, 8, 'Feature Request', ARRAY['import', 'integration']);