-- Seed data for AgilePM Foundation course
DO $$
DECLARE
  v_course_id uuid;
  v_mod_id uuid;
BEGIN
  -- Insert course
  INSERT INTO public.courses (slug, title, description)
  VALUES (
    'agilepm-foundation',
    'AgilePM Foundation',
    'A self-paced preparation course for the AgilePM Foundation certification, based on the AgilePM v3 Edition 2 reference book.'
  ) RETURNING id INTO v_course_id;

  -- ============================================================
  -- Module 1: Introduction and context (3 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 1: Introduction and context', 1)
  RETURNING id INTO v_mod_id;

  -- Lesson 1.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'The Agile Business Consortium and Business Agility', 'text', '7 min', 'Ch. 1 and 2.1', NULL,
  $notes$<div class="ref">Chapters 1 and 2.1</div><div class="vt">The Agile Business Consortium and Business Agility</div><div class="vb">In the early 1990s, business leaders were frustrated by costly, rigid, or unreliable software development projects. Several organisations formed a not-for-profit consortium to define an industry standard. This was DSDM, with the DSDM Consortium formed in 1994. In 2016 it rebranded as the Agile Business Consortium. Its mission is to make the world of work better by advancing Business Agility worldwide. AgilePM fits into the "change" segment of the broader Framework for Business Agility (FBA), which includes agile culture, leadership, governance, strategy, operations, and business change.</div><div class="co">The ABC defines Business Agility as: "A progressive, people-centric approach to all aspects of business that is transforming how organisations operate and succeed in the modern world." It is achieved by inspiring, enabling, and harnessing the collaborative and creative ways of working in an organisation's people to meet its core purpose.</div><div class="vb">DSDM originally covered two areas: Product Development and Project Management. The Project Management approach became AgilePM, first released in 2010. Over 250,000 people worldwide have become AgilePM certified, making it the most popular agile project management qualification globally. AgilePM offers clear roles, incremental delivery, and a strong emphasis on business and customer engagement with value-driven outcomes. It enables agile project delivery across a range of business contexts, not just within software or IT.</div>$notes$,
  1);

  -- Lesson 1.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'The Agile Manifesto and its principles', 'text', '8 min', 'Ch. 2.1.3 and 2.1.4', NULL,
  $notes$<div class="ref">Chapter 2.1.3 and 2.1.4</div><div class="vt">The Agile Manifesto and Its Principles</div><div class="vb">In February 2001, 17 software development experts met in Snowbird, Utah. They shared experiences and discussed similarities in their new ways of building software. This group, the Agile Alliance, published the Manifesto for Agile Software Development. Key people included Ken Schwaber and Jeff Sutherland (who created Scrum) and Arie Van Bennekum (who was part of the team behind AgilePM).</div><div class="co">The ABC adapted the four Manifesto values for a wider context, replacing "software" with "solutions": Individuals and interactions over processes and tools. Working solutions over comprehensive documentation. Customer collaboration over contract negotiation. Responding to change over following a plan. The right-hand items still have value - the left-hand items are valued more.</div><div class="vb">The 12 principles as enhanced by the ABC for the agile project context: (1) Satisfy the customer through early and continuous delivery of value. (2) Welcome change, even late in the evolution of a solution. (3) Deliver working solutions frequently, with a preference for the shorter timescale. (4) All parties must work together daily throughout the project. (5) Build projects around motivated individuals. (6) Face-to-face conversation is the most effective method of conveying information. (7) Working solutions are the primary measure of progress. (8) Agile processes promote sustainable delivery. (9) Continuous attention to technical excellence enhances agility. (10) Simplicity - maximising the amount of work not done - is essential. (11) The best outcomes emerge from self-organising teams. (12) At regular intervals, the team reflects on how to become more effective.</div>$notes$,
  2);

  -- Lesson 1.3
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'AgilePM and Scrum together', 'video', '9 min', 'Ch. 2.5', NULL,
  $notes$<div class="ref">Chapter 2.5</div><div class="vt">AgilePM and Scrum Together</div><div class="vb">This reference book uses Scrum, based on The Scrum Guide 2020, as the default method for organising team-based product development. However, the use of Scrum is extended through AgilePM so it can fit into wider project and organisational settings. Scrum is not the only option - other team-based methods can be used instead of or alongside Scrum within the same AgilePM project.</div><div class="co">AgilePM began as DSDM, which always focused on the project as a whole - not just product delivery. It was built to work in large, complex organisations. Scrum focuses on product development. Combining the two brings the full project lifecycle, governance structure, and defined project roles together with Scrum's delivery engine.</div><div class="vb">Scrum has a fixed structure - its roles, artifacts, events, and rules are considered unchangeable. All core elements must be present and followed for a team to be using Scrum effectively. AgilePM, by contrast, is intended to be flexible and tailored to meet the specific needs of each organisation and project. AgilePM can support any team-based development approach, not just Scrum, while still providing full project-level structure and guidance.</div>$notes$,
  3);

  -- ============================================================
  -- Module 2: AgilePM fundamentals (2 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 2: AgilePM fundamentals', 2)
  RETURNING id INTO v_mod_id;

  -- Lesson 2.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'The philosophy and project variables', 'video', '9 min', 'Ch. 4.1 and 4.2', NULL,
  $notes$<div class="ref">Chapters 4.1 and 4.2</div><div class="vt">The Philosophy and Project Variables</div><div class="co">The AgilePM philosophy is that: "Best value emerges when projects are aligned to clear goals, deliver frequently and involve the collaboration of motivated and empowered people."</div><div class="vb">This happens when every stakeholder understands and supports the business vision, is empowered to make decisions in their area of expertise, collaborates to create and deliver the solution on time, and accepts that changes will be required as the project progresses. In this context, value refers to the balanced, expressed needs of the appropriate stakeholders, which could be Business Sponsors, Operational Users, and customer or citizen users of the solution.</div><div class="vb">Projects must balance four key variables: Time, Cost, Quality, and Features. Non-agile approaches fix the features and allow time and cost to flex, using contingency as extra time and budget. AgilePM turns this upside down: it fixes time and cost while allowing features to be flexible. Contingency is managed through MoSCoW prioritisation across a range of Project Artifacts.</div><div class="co">Quality is never compromised in an AgilePM project. The approach requires: prioritisation of features using MoSCoW to deliver business value; delivery of highest-value features first; and close daily collaboration between Delivery Team(s) and the Value Ownership roles to delay or exclude lower-priority features when necessary.</div><div class="vb">AgilePM recommends that contingency be in the Features to be delivered. The small loss of some lower-priority features is far outweighed by the benefits of delivering on time and within budget. Additionally, there is always the option to invest extra time and resources later if missing features become essential.</div>$notes$,
  1);

  -- Lesson 2.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'The eight AgilePM principles', 'text', '14 min', 'Ch. 4.3', NULL,
  $notes$<div class="ref">Chapter 4.3</div><div class="vt">The Eight AgilePM Principles</div><div class="vb">AgilePM projects follow eight key principles. These align with the ABC's adaptation of the four Agile Manifesto values. The principles are enabled through practices: Iterative Development, Timeboxing (including Sprints), MoSCoW Prioritisation, Modelling, and Facilitated Workshops.</div><div class="co">1. Focus on the Business Need - Every decision should be made with the project vision in mind. A strong Business Case creates urgency for delivery and keeps all stakeholders focused on business goals.</div><div class="co">2. Deliver on Time - Delivering Solution Increments on time is often the most important goal. If delivery is delayed it can lose value, particularly if it depends on market opportunities or legal deadlines. Timeboxing maintains focus and demonstrates progress.</div><div class="co">3. Collaborate - Teams that work closely together with a shared commitment achieve better results. Effective collaboration results in better understanding, greater creativity, more accurate plans, and higher quality solutions. When collaboration is strong, a team can achieve more together than its individual members could alone.</div><div class="co">4. Never Compromise Quality - The expected quality level should be defined at the beginning. The solution should be fit-for-purpose - "good enough" to meet business needs. Quality is never compromised while maintaining agility and flexibility.</div><div class="co">5. Build Incrementally from Firm Foundations - Gain a high-level understanding early of the business problem, the proposed solution, and associated risks. Once foundations are in place, deliver incrementally to build stakeholder confidence, provide continuous feedback, and ensure the solution stays aligned with business needs.</div><div class="co">6. Develop Iteratively - Work closely with the customer to continuously improve the solution. Short development cycles provide frequent demonstrations (transparency), regular reviews (inspection), and allow adjustments based on feedback (adaptation). Most solutions are not perfect on the first attempt.</div><div class="co">7. Communicate Continuously and Clearly - Poor communication is one of the main reasons projects fail. AgilePM includes practices (Workshops, Modelling) and Scrum has events (Daily Scrums, Sprint Reviews) to improve communication. Documentation should only be created if it adds value, helps with solution development, or is essential for safety or regulatory compliance.</div><div class="co">8. Demonstrate Control - The project must always be under control, and this control must be visible. Transparency means making all work visible, establishing clear accountabilities, and measuring progress based on working solutions - not just completed tasks.</div>$notes$,
  2);

  -- ============================================================
  -- Module 3: Scrum (3 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 3: Scrum', 3)
  RETURNING id INTO v_mod_id;

  -- Lesson 3.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Scrum theory, values, and the Scrum team', 'text', '8 min', 'Ch. 3.1 - 3.4', NULL,
  $notes$<div class="ref">Chapter 3 (Scrum Guide 2020)</div><div class="vt">Scrum Theory, Values, and the Scrum Team</div><div class="vb">Scrum is a process framework used to develop and maintain complicated products, especially where work is done by small, collaborative, and self-organising teams. The core ideas were first introduced in 1986 by Professors Takeuchi and Nonaka and later adapted for software development by Ken Schwaber and Jeff Sutherland in the 1990s.</div><div class="co">The core idea at the centre of Scrum is Empirical Process Control - making decisions based on what is known and observed, not on fixed predictions. It is built on three pillars: Transparency (a clear, shared understanding of the work), Inspection (regularly checking progress), and Adaptation (adjusting based on what has been learned).</div><div class="vb">The five Scrum values are: Commitment, Focus, Openness, Respect, and Courage. The Scrum Team consists of three accountabilities: Developers (who create any aspect of a usable Product Increment each Sprint), the Product Owner (accountable for maximising the value of the product), and the Scrum Master (accountable for the effectiveness of the Scrum Team).</div><div class="co">In AgilePM: the Product Owner corresponds to the Business Ambassador role. The Scrum Master corresponds to the Team Leader role. "We use the word 'developers' in Scrum not to exclude, but to simplify" - it refers to anyone contributing to creating a usable Product Increment in a Sprint.</div>$notes$,
  1);

  -- Lesson 3.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Scrum events', 'text', '7 min', 'Ch. 3.5', NULL,
  $notes$<div class="ref">Chapter 3.5 (Scrum Guide 2020)</div><div class="vt">Scrum Events</div><div class="vb">Scrum defines five events. Each is an opportunity to inspect and adapt. In AgilePM, a Sprint is referred to as a Delivery Timebox - the terms are used interchangeably throughout the reference book.</div><div class="co">The Sprint - A fixed-length event of one month or less during which a usable Product Increment is created. A new Sprint starts immediately after the previous one concludes. All other events happen within a Sprint.</div><div class="co">Sprint Planning - Initiates the Sprint by planning the work to be performed. The whole Scrum Team collaborates to address three topics: why is this Sprint valuable? What can be done this Sprint? How will the chosen work get done?</div><div class="co">Daily Scrum - A 15-minute event for the Developers to inspect progress toward the Sprint Goal and adapt the Sprint Backlog as necessary.</div><div class="co">Sprint Review - Inspects the outcome of the Sprint and determines future adaptations. The Scrum Team presents results of their work to stakeholders. The Product Backlog may also be adjusted to reflect new opportunities.</div><div class="co">Sprint Retrospective - Plans ways to increase quality and effectiveness. The Scrum Team inspects how the last Sprint went regarding individuals, interactions, processes, tools, and their Definition of Done.</div>$notes$,
  2);

  -- Lesson 3.3
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Scrum artifacts and the backlog hierarchy', 'text', '7 min', 'Ch. 3.6 and 8.1', NULL,
  $notes$<div class="ref">Chapter 3.6 and 8.1</div><div class="vt">Scrum Artifacts and the Backlog Hierarchy</div><div class="vb">The three Scrum artifacts are: the Product Backlog, the Sprint Backlog, and the Product Increment. Each artifact has a commitment that provides transparency and focus against which progress can be measured.</div><div class="co">Product Backlog (commitment: Product Goal) - An emergent, ordered list of what is needed to improve the product. It is the single source of work undertaken by a Delivery Team to fulfil a Product Goal. There may be multiple Product Goals during a project, but a Delivery Team focuses on one at a time.</div><div class="co">Sprint Backlog (commitment: Sprint Goal) - The output of Sprint Planning. It contains the Sprint Goal, the Product Backlog Items to be done, and a plan for delivering the Product Increment. In AgilePM, MoSCoW prioritisation is applied to the Product Backlog Items selected for the Sprint.</div><div class="co">Product Increment (commitment: Definition of Done) - A concrete stepping stone toward the Product Goal. In AgilePM, Product Increments may combine to create a Solution Increment. When a Solution Increment is deployed, it becomes or adds to the overall Deployed Solution.</div><div class="vb">AgilePM adds a Solution Backlog above the Product Backlog. The Solution Backlog is an emergent ordered list of everything known to be needed for the Solution - not just one product, but everything needed to make the solution valuable. Less complex projects delivering a single product may not require a separate Solution Backlog.</div>$notes$,
  3);

  -- ============================================================
  -- Module 4: Roles and organisation (3 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 4: Roles and organisation', 4)
  RETURNING id INTO v_mod_id;

  -- Lesson 4.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Project roles and the three domains', 'video', '10 min', 'Ch. 5.2 and 5.3', NULL,
  $notes$<div class="ref">Chapters 5.2 and 5.3</div><div class="vt">Project Roles and the Three Domains</div><div class="vb">All roles in an AgilePM project fit into one of three domains of interest.</div><div class="co">Value Ownership - Concerned with representing organisation, customer, and user stakeholders to ensure their needs are reflected in the evolving solution. Project Roles: Business Sponsor and Business Visionary. Delivery Team role: Product Owner (or Business Ambassador).</div><div class="co">Solution Delivery - About all matters related to the creation of the solution, including the approach used to deliver it. Project Role: Solution Architect. Delivery Team role: Developers.</div><div class="co">Delivery Enablement - Relates to leading an effective agile project as defined by the AgilePM approach. Project Role: Project Manager. Delivery Team role: Scrum Master (or Team Leader).</div><div class="vb">The Business Sponsor owns the project and is ultimately accountable for project success. They own the Business Case and hold the project budget. The Business Visionary defines the vision and desired outcomes and owns the Solution Backlog - they can be likened to a Product Owner for the overall project solution. The Solution Architect owns the solution design and delivery approach. The Project Manager is accountable for establishing and managing an effective project environment in accordance with the AgilePM framework.</div><div class="vb">In v3, "Project Leadership Roles" has been renamed "Project Roles" to address issues with hierarchy. Leadership in AgilePM is distributed, not positional.</div>$notes$,
  1);

  -- Lesson 4.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Delivery team roles', 'text', '8 min', 'Ch. 5.4', NULL,
  $notes$<div class="ref">Chapter 5.4</div><div class="vt">Delivery Team Roles</div><div class="vb">Agile Delivery Teams are cross-functional and self-managing. A Scrum Team is the model assumed in this reference book. However, organisations may form self-managing delivery teams that do not strictly follow the Scrum Guide - this acknowledges real-world considerations such as organisational maturity, delivery context, or use of alternative frameworks such as Kanban or AgilePM v2.</div><div class="co">The Product Owner (or Business Ambassador) is accountable for maximising the value of the product developed by their Delivery Team. On complex projects, Product Backlogs are pulled from a Solution Backlog to ensure strategic alignment - making the Business Visionary a major collaborator for both roles. Any changes to the Product Backlog must be made by influencing the Product Owner or Business Ambassador.</div><div class="co">The Scrum Master (or Team Leader) is accountable for establishing Scrum and for the effectiveness of the team. The role is facilitative and coaching in style - more asking than telling. Both roles should aspire to be true leaders whose success is defined by the effectiveness of their Delivery Team. Geoff Watts' two commandments: first ask the team, and make yourself redundant.</div><div class="co">Developers are anyone working on tasks from the Sprint Backlog. Business Analysis is not tied to a single role - it can influence any or all aspects of a project. Business Analysts are recognised as Developers in AgilePM. In many organisational contexts there may be no formal Business Analyst job title and business analysis skills are shared across the Project Organisation.</div><div class="vb">AgilePM also recognises three Advisor Roles: Business Advisors (collaborating with value ownership roles), Solution Advisors (collaborating with solution delivery roles), and Process Advisors such as an Agile Coach or Workshop Facilitator. Advisor roles are context specific and may not always be needed.</div>$notes$,
  2);

  -- Lesson 4.3
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Collaboration and communication', 'video', '10 min', 'Ch. 6', NULL,
  $notes$<div class="ref">Chapter 6</div><div class="vt">Collaboration and Communication</div><div class="vb">Collaboration and clear communication play a crucial role in project success. AgilePM recognises their importance directly in two of its eight core principles: Principle 3 (Collaborate) and Principle 7 (Communicate continuously and clearly). These describe essential "soft skills" required for effective teamwork.</div><div class="co">Collaboration means working together towards a shared goal. People who collaborate effectively have a shared purpose, help one another, respect each other's contributions, adapt to changes together, take initiative, and trust their teammates. The AgilePM Principles, Scrum Values, and the Nine Principles of Agile Leadership all reinforce collaboration through Focus, Commitment, Respect, Openness, and Courage.</div><div class="vb">Poor communication is a major reason why projects fail. Common causes include: not using a shared language, lack of access to the right people, failing to identify key stakeholders, not agreeing on communication methods, and over-reliance on written communication instead of face-to-face discussion.</div><div class="co">Principle 6 of the Agile Manifesto states: "The most efficient and effective method of conveying information to and within any team is face-to-face conversation." Communication choices range from face-to-face (most effective) through virtual meetings, instant messaging, social media, email, and documents. Teams should choose the best method for each situation.</div><div class="vb">AgilePM encourages facilitated workshops and modelling to help teams reach shared understanding. Facilitated Workshops involve a workshop owner with a clear goal, carefully selected participants with the knowledge and authority to make decisions, and an independent Workshop Facilitator. Modelling is a method of visually representing a problem or solution. As Jim Highsmith stated: "Documentation is not understanding, process is not discipline, formality is not skill."</div>$notes$,
  3);

  -- ============================================================
  -- Module 5: The project lifecycle (4 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 5: The project lifecycle', 5)
  RETURNING id INTO v_mod_id;

  -- Lesson 5.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Increments of value and time', 'video', '9 min', 'Ch. 7.1', NULL,
  $notes$<div class="ref">Chapter 7.1</div><div class="vt">Increments of Value and Increments of Time</div><div class="vb">AgilePM makes a clear distinction between a Product (delivered by one or more Agile Delivery Teams) and the Solution required to meet the overarching desired project outcome, which may be a combination of multiple products and other items such as training, communications, and business change deliverables.</div><div class="co">Two types of value increment: Product Increments are stepwise refinements of a Product that meet the agreed Definition of Done. Solution Increments are stepwise refinements of the overall Solution - delivered increments of several products may be combined to create a Solution Increment. When a Solution Increment is deployed it becomes or adds to the overall Deployed Solution.</div><div class="co">Three types of timebox: the Project Timebox (the full project from start to finish, covering all elements under the responsibility of the Project Roles), the Project Increment Timebox (a subdivision of the Project Timebox, bound at each end by a revisiting of Foundations), and Delivery Timeboxes (Sprints). In v3, "Tranche" has been replaced by "Project Increment."</div><div class="vb">Each nested timebox increases opportunities to inspect and adapt, ensuring that learning informs direction at multiple levels within the project structure. The lifecycle can be configured as: a simple single Project Increment; a multi-increment lifecycle; a continuous delivery lifecycle with return to Foundations between increments; or a continuous delivery lifecycle with no return to Foundations and ongoing planning via cross-team refinement.</div>$notes$,
  1);

  -- Lesson 5.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Pre-project and Feasibility phases', 'text', '7 min', 'Ch. 7.3 and 7.4', NULL,
  $notes$<div class="ref">Chapters 7.3 and 7.4</div><div class="vt">Pre-project and Feasibility Phases</div><div class="vb">The Pre-Project Phase ensures that only the right projects get started and that each project is correctly set up with clearly stated goals before work begins. In small or informal settings it can be as simple as a conversation between someone with an idea and a potential sponsor. In larger organisations it may require a written proposal for an investment committee. The Terms of Reference is the potential artifact - a short milestone document to present a new project idea.</div><div class="co">The Feasibility Phase is a high-level assessment to determine if the project is likely to be desirable, feasible, and viable. It examines: solution feasibility (can a solution be built?), stakeholder desirability and viability (will it deliver value and be cost-effective?), and people's capability (is there the right culture, experience, and leadership to work in an agile way?). The intention is to keep Feasibility as light and short as possible.</div><div class="vb">The Project Roles must use the Project Approach Questionnaire (PAQ) during Feasibility to assess project risks, especially those related to complexity. Feasibility Prototypes, Technical Spikes, and early user research may be created to validate ideas before full delivery begins. The Business Sponsor, Business Visionary, Solution Architect, and Project Manager all have input into the Feasibility Phase.</div><div class="co">Potential artifacts in Feasibility: Business Case (Recommended) - brief, covering purpose, estimated costs and benefits, and constraints. Delivery Plan (Required) - high-level, with indicative delivery dates and an outline of potential Project Increments. Management Approach Definition (Recommended). Solution Backlog, Solution Architecture Definition, and Delivery Approach Definition are all Optional at this stage.</div>$notes$,
  2);

  -- Lesson 5.3
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Foundations phase', 'text', '10 min', 'Ch. 7.5', NULL,
  $notes$<div class="ref">Chapter 7.5</div><div class="vt">Foundations Phase</div><div class="vb">The Foundations Phase comes after Feasibility, but in longer or more complex projects it could be revisited after each Project Increment. The main goal of the first Foundations Phase is to create a strong and lasting foundation. It focuses on three areas: Value (ensuring alignment with stakeholder goals), Solution (defining what will be built), and Process (planning how the project will be run).</div><div class="co">The Foundations Phase expands on Feasibility by providing a deeper understanding of: why the project is being done (Business Case), what kind of Solution will be built (Solution Architecture Definition), and how the Solution will be delivered (Delivery Approach Definition). The finer details are left for the Delivery Phase. Keeping scope high-level helps avoid delays and ensures the Foundations Phase lasts only a few weeks, even for large projects.</div><div class="vb">By the end of Foundations there should be a clear, high-level Delivery Plan covering what needs to be done, who will do it, and when and where it will happen. The Solution Backlog and Delivery Plan should be baselined for the next Project Increment. AgilePM follows the principle of "just enough detail, just in time." Adding too much detail too early makes the project more vulnerable to VUCA.</div><div class="co">The PAQ should be reviewed at the end of Foundations and on any subsequent passes to ensure that previous tailoring decisions are still relevant. When the Delivery Plan includes multiple Project Increments, the process loops back to Foundations at the end of each increment - an opportunity to evaluate and improve agility and governance effectiveness.</div>$notes$,
  3);

  -- Lesson 5.4
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Delivery, Deployment, and Realization phases', 'video', '11 min', 'Ch. 7.6 - 7.8', NULL,
  $notes$<div class="ref">Chapters 7.6, 7.7, and 7.8</div><div class="vt">Delivery, Deployment, and Realization Phases</div><div class="vb">The Delivery Phase builds upon the solid foundation created in the earlier phases. With each Sprint, Delivery Teams explore the detail of Product Backlog items, deliver to meet the Definition of Done, and aim to deliver a usable Product Increment each Sprint. The phase was renamed from "Development" in v2 to "Delivery" in v3 to emphasise the continuous delivery mindset.</div><div class="co">AgilePM recommends delivering a "vertical" or "Done" product slice that contains all required elements (user interface, business logic, data layer). Delivering a "horizontal" layer of technology is not beneficial - the other layers still need to be delivered in subsequent Sprints to make the Product Increment usable. Delivering components that are not immediately usable delays value delivery and may cause integration problems.</div><div class="vb">The Deployment Phase happens in three sequential steps: Assemble (bringing together all parts of the Solution, including software, training materials, process descriptions, and any regulatory documentation), Review (a final quality check and formal decision to deploy or not), and Deploy (making the solution available for actual use). Ideally Deployment runs ongoing in line with the Delivery Phase. In mature environments, Solution and Product Increments may be deployed multiple times in a Sprint.</div><div class="co">The Realization Phase ensures the expected benefits of the solution actually happen over time. The Business Sponsor is accountable for return on investment. The Business Visionary is responsible for embedding the solution. AgilePM recommends funding an ongoing Product Management function after the project ends - ideally an appropriately-funded small agile Delivery Team responsible for continuous improvement.</div>$notes$,
  4);

  -- ============================================================
  -- Module 6: Requirements and estimation (3 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 6: Requirements and estimation', 6)
  RETURNING id INTO v_mod_id;

  -- Lesson 6.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Requirements and user stories', 'video', '10 min', 'Ch. 8.1 and 8.2', NULL,
  $notes$<div class="ref">Chapter 8.1 and 8.2</div><div class="vt">Requirements and User Stories</div><div class="vb">A requirement is a business or user need to be met by the Solution. In AgilePM and Scrum, requirements are often written as User Stories. A solution includes all the necessary elements - products, services, processes, and people - required to address a business problem or opportunity. Adding a requirement to a backlog is not a guarantee it will be delivered, as the understanding of solution value is emergent and priorities could change.</div><div class="co">The widely used User Story format, invented by agile coach Rachel Davies: As a (who) / I want (what) / So that (why). This gives who, what, and why in a succinct statement. More traditional formats like "The solution shall..." focus only on features rather than user needs. Requirements can be functional (what the solution must do) or non-functional (how well it must perform).</div><div class="vb">User Stories can be written at different levels of detail: Epic User Stories are broad and high-level, used in Feasibility. User Stories are more detailed but still relatively high-level, used in Foundations. Fine-grained User Stories are ready for development, used in Sprint Planning during the Delivery Phase. New requirements can emerge during Delivery and are added to the Product Backlog in an unrefined state, then refined until ready for an upcoming Sprint.</div><div class="co">A User Story has three (or four) Cs: the Card (brief, a conversation starter), the Conversation (wait until the last responsible moment to refine details), the Confirmation (Acceptance Criteria defining the specific conditions the story must meet), and the Context (how the story connects to other stories and supports prioritisation).</div><div class="vb">Bill Wake's INVEST model for well-constructed User Stories: Independent, Negotiable, Valuable, Estimable, Small (enough), Testable. These criteria help User Stories fit smoothly into AgilePM's iterative and incremental approach.</div>$notes$,
  1);

  -- Lesson 6.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Definition of Done and Definition of Ready', 'text', '7 min', 'Ch. 8.2.3.6 and 8.2.3.7', NULL,
  $notes$<div class="ref">Chapter 8.2.3.6 and 8.2.3.7</div><div class="vt">Definition of Done and Definition of Ready</div><div class="co">The Definition of Done (DoD) is a shared understanding of what it means for a product or solution increment to be complete. The Scrum Guide defines it as: "A formal description of the state of the Increment when it meets the quality measures required for the product." Product Backlog items that do not meet the DoD are still undone work that should remain visible on the Product Backlog.</div><div class="vb">A generalised DoD covers: it works and is built as intended (meets Acceptance Criteria); it has been reviewed and tested (by someone other than the builder); it looks and feels right (meets agreed standards); it is ready for the customer (no extra work needed before release or use); it is documented if needed; and it is approved by the Product Owner or Business Ambassador. Acceptance Criteria are often confused with the DoD - meeting Acceptance Criteria is a minimum criterion for all requirements, usually just one element of the DoD.</div><div class="co">Where a solution is made up of multiple interrelated products, a Solution-level Definition of Done ensures the overall solution is complete, fit for business use, and ready for operational deployment. It must ensure all components conform to the delivery practices in the Delivery Approach Definition (DAD) and the architectural constraints in the Solution Architecture Definition (SAD). As the project moves through the lifecycle, the DoD can evolve toward an ideal state where every increment can be released independently.</div><div class="co">The Definition of Ready is a list of criteria that must be met for a Product Backlog item to be ready for a Sprint. Key criteria include: clearly defined scope; value identified; small enough to start; Acceptance Criteria agreed; people and resources available; dependencies and risks understood; estimated or timeboxed; and Delivery Team agreement. When User Stories are used, INVEST is a useful basis for a team's Definition of Ready.</div>$notes$,
  2);

  -- Lesson 6.3
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Estimating the work', 'text', '9 min', 'Ch. 8.3', NULL,
  $notes$<div class="ref">Chapter 8.3</div><div class="vt">Estimating the Work</div><div class="vb">In agile projects, estimating must account for iterative development, incremental delivery, and deferring details until the last responsible moment. Early estimates are made with limited information and are expected to change as the Delivery Team gains a better understanding of stakeholder needs, learns more about the solution by building it, and improves its ways of working. This contrasts with sequential project management, where estimates are based on detailed analysis and design created before work begins.</div><div class="co">Four key points when estimating: (1) Include contingency - there are always unknowns; MoSCoW prioritisation handles this uncertainty. (2) Estimate only as precisely as needed - overly detailed estimates too early can be misleading. (3) Involve the people doing the work - the most useful estimates come from those who will deliver it. (4) Continuously revalidate estimates - as understanding improves, update estimates to reflect emergent knowledge.</div><div class="vb">Two common estimating styles: Estimating by analogy (comparative estimating) - comparing tasks to past similar work, using techniques such as T-Shirt Sizing (Small/Medium/Large/XL) or Story Points. Estimating by decomposition - breaking tasks down into smaller parts and estimating each individually. Good practice is to use multiple techniques and involve multiple experts to increase accuracy and reduce bias.</div><div class="co">Velocity measures how many Story Points a Delivery Team has done on average in previous Sprints. It is used to forecast how much can be done in upcoming Sprints. Velocity is unique to each team - it cannot be compared across different teams. Changes in team composition affect velocity. It is a measure of output, not outcomes - project organisations should be wary of using velocity as the sole measure of delivery progress.</div><div class="vb">The Estimating Cycle: Feasibility Phase - rough estimates using T-Shirt Sizing, ranges given (e.g. 100-200 team days). Foundations Phase - more refined estimates as Epics are broken into User Stories; both analogy and decomposition used; estimates refined to support the Business Case and plan the next Project Increment. Delivery Phase - estimates updated using real velocity data; decomposition used during Sprint Planning to break Product Backlog Items into tasks.</div>$notes$,
  3);

  -- ============================================================
  -- Module 7: MoSCoW and planning (2 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 7: MoSCoW and planning', 7)
  RETURNING id INTO v_mod_id;

  -- Lesson 7.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'MoSCoW prioritisation', 'video', '10 min', 'Ch. 9', NULL,
  $notes$<div class="ref">Chapter 9</div><div class="vt">MoSCoW Prioritisation</div><div class="vb">MoSCoW prioritisation is only effective when used together with a specified timeframe. It helps decide the priority of tasks to be completed within a fixed timebox. The word MoSCoW stands for Must Have, Should Have, Could Have, and Won't Have This Time.</div><div class="co">Must Have requirements form the Minimum Usable SubseT (MUST) - what must be delivered within the set timebox. A Must Have requirement means: the project would not deliver its essential value without it; it is legally required; it is essential for safety; the solution cannot function without it; or the solution would not be marketable without it. AgilePM advises that Must Haves should take up no more than 60% of total effort available. If the effort needed to deliver Must Haves exceeds 60%, the guarantee to deliver this minimum is put at risk.</div><div class="co">Should Have requirements are important but not vital - the solution will still be viable without them, though there may be some pain. Could Have requirements are wanted but less important - they act as the main pool of contingency and are the first features to be removed if the deadline is at risk. AgilePM suggests allocating about 20% of total effort to Could Have items. Won't Have This Time requirements will not be delivered in the specified timeframe - documenting them prevents them being reintroduced as forgotten or new requirements.</div><div class="vb">MoSCoW can be applied at three different levels: Project-level (what must be delivered by the end of the project), Project Increment-level (what must be delivered within a Project Increment), and Delivery Timebox/Sprint-level (what must be delivered in the next Sprint). A requirement's priority at one level may differ from its priority at another level.</div><div class="co">A useful technique for assigning priorities: start with all requirements as Won't Haves and only promote them if there is strong justification. For each Must Have, ask: "Would the project be cancelled if this requirement were not met?" If yes, it is a true Must Have. If no, reconsider it as a Should Have or Could Have. If a workaround exists, it is not a Must Have.</div>$notes$,
  1);

  -- Lesson 7.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Planning through the lifecycle', 'text', '9 min', 'Ch. 10', NULL,
  $notes$<div class="ref">Chapter 10</div><div class="vt">Planning Through the Lifecycle</div><div class="vb">AgilePM describes three key planning concepts: outcome-based planning (focus on delivering real business value), planning to sensible horizons (plan in appropriate detail for different levels of timebox), and plan and re-plan using the most up-to-date estimates (continuously refine plans based on the latest available information).</div><div class="co">AgilePM also defines four tracking and control concepts: outcome-based measurement (track progress based on delivered value, not tasks completed), transparency of process and progress (make project processes and progress visible to all stakeholders), responding to change (inspect and adapt plans quickly), and management by exception (only escalate issues when necessary, reducing unnecessary reporting and encouraging self-management).</div><div class="vb">Planning happens at three different time levels: long-term planning covers the entire project and post-project activities; medium-term planning covers the current or next Project Increment; and short-term planning covers the current or next Sprint. Plans are not fixed and must adapt to real-world changes including shifting stakeholder needs and unplanned organisational changes.</div><div class="co">Progress should be measured based on working solutions rather than completed tasks. A partially completed feature has less business value than a feature that has not started, as incomplete work adds complications without adding value. Reporting should be structured enough to provide continuous insight, allowing the Project Roles to assess progress and adjust as needed.</div>$notes$,
  2);

  -- ============================================================
  -- Module 8: Risk and governance (2 lessons)
  -- ============================================================
  INSERT INTO public.modules (course_id, title, position)
  VALUES (v_course_id, 'Module 8: Risk and governance', 8)
  RETURNING id INTO v_mod_id;

  -- Lesson 8.1
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Risk management and the PAQ', 'text', '9 min', 'Ch. 11', NULL,
  $notes$<div class="ref">Chapter 11</div><div class="vt">Risk Management and the PAQ</div><div class="vb">In a project, risk generally refers to the possibility of something happening that could unexpectedly affect the project's goals. Risks may be internal to the Project Organisation or external. AgilePM is designed to handle VUCA in the project environment by using well-established agile philosophy, principles, and practices; preventing delays caused by rigid rule-based approaches; making sure quality, risk, and governance are considered from the outset; and continuously reviewing and managing risks as part of backlog refinement.</div><div class="co">Because risk management is naturally part of AgilePM's regular day-to-day activities, there should be no need for a separate, formal risk management process, except perhaps in highly regulated or safety-related contexts. Agile projects, which prioritise adaptability and collaboration, are generally less affected by VUCA compared to non-agile projects that depend on rigid plans and documentation.</div><div class="vb">Risk ownership in AgilePM: the Business Visionary is responsible for identifying and owning Value Ownership-based risk. The Solution Architect is responsible for Solution Delivery-based risk. The Project Manager is responsible for Delivery Enablement risk, including project organisation, schedule, and internal and external dependencies.</div><div class="co">The Project Approach Questionnaire (PAQ) helps identify possible risks when using the AgilePM approach. It is designed to guide adjustments to reduce risks and improve project success. If all project team members agree with every PAQ statement, the risk of using AgilePM is low. If any statement is considered not to be true, it indicates a risk that must be resolved. The first PAQ assessment is usually done in the Feasibility Phase. It should be reviewed again at the end of Foundations and every time Foundations is revisited.</div><div class="vb">PAQ statements cover areas including: team understanding of the combined AgilePM and Scrum approach; Business Sponsor and Business Visionary ownership; clarity of the business vision; acceptance of on-time delivery as the primary measure of success; acceptance that requirements can be prioritised and scope can flex; willingness to define requirements at a high level initially; and readiness for commercial arrangements that support agile working.</div>$notes$,
  1);

  -- Lesson 8.2
  INSERT INTO public.lessons (module_id, title, type, duration, chapter_ref, video_url, notes_html, position)
  VALUES (v_mod_id, 'Governance, compliance, and Project Artifacts', 'text', '8 min', 'Ch. 12', NULL,
  $notes$<div class="ref">Chapter 12</div><div class="vt">Governance, Compliance, and Project Artifacts</div><div class="vb">At first glance, governance and empiricism may seem like opposites. Governance is often about strictly following rules, while empiricism values adapting rules to achieve better outcomes. In the project context, Governance means the set of processes, structures, and controls that ensure a project is well managed and meeting its objective. When creating a framework of governance for an agile project, it is important to focus on the purpose behind the governance, then design processes that support that purpose without limiting agility.</div><div class="co">Compliance-based governance (the non-agile default) tends to prioritise: processes and tools over individuals and interactions; comprehensive documentation over working solutions; contract negotiation over customer collaboration; and following a plan over responding to change. These are the Agile Manifesto statements in reverse. If inappropriate governance is applied to an agile project, it may undermine agility and impact the outcome.</div><div class="vb">Governance of agile delivery in AgilePM focuses on: whether people are working together well to make steady progress; whether everyone in the Value Ownership, Solution Delivery, and Delivery Enablement roles is equally committed and focused; and whether the right solution is being built for the organisation. As Jim Highsmith stated: "Documentation is not understanding, process is not discipline, formality is not skill."</div><div class="co">In v3, "Work Products" has been replaced by "Project Artifacts." Most Project Artifacts are evolutionary - they are created early with light content and progressively elaborated. They should only be created if they add real value. The RACI (Responsible, Accountable, Consulted, Informed) in Appendix A clarifies who does what for each artifact across the lifecycle. Financial governance links the Business Case to ongoing delivery decisions - if the expected return on investment is no longer achievable with the remaining Must Haves, the project should be stopped.</div>$notes$,
  2);

END $$;
